apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: This line is waaaaaaaaaay too long it keeps going on and on and on and on  # Line is too long
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-python
          env:
            - name: TARGET
              value: "Python Sample v1"
              - name: TEST  # Wrong indentation
                value   : "value"  # Too many spaces between colon
