apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: This line is waaaaaaaaaay too long asdasdsddddddddddddddddddddddddddd
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/helloworld-python   
          env:
            - name: TARGET
              value: "Python Sample v1"
              - name: TEST
                value   : "value"